### PR TITLE
erlang: add the missing src directory of patched os_mon

### PR DESCRIPTION
**Pull request by bhuztez**

### CODE REVIEW

**Comment by nyh** [comment]
This patch includes over a thousand lines of Erlang code - where does it
come from? If it comes from the Erlang distribution itself, why do we need
to put it in osv-apps.git?

On Mon, May 4, 2015 at 12:05 PM, bhuztez <notifications@github.com> wrote:

> bhuztez wants to merge 1 commit into cloudius-systems:master from
> bhuztez:fix-missing-src:
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/cloudius-systems/osv-apps/pull/24
> Commit Summary
>
>    - erlang: add the missing src directory of patched os_mon
>
> File Changes
>
>    - *M* erlang/Makefile
>    <https://github.com/cloudius-systems/osv-apps/pull/24/files#diff-0>
>    (2)
>    - *M* erlang/os_mon/.gitignore
>    <https://github.com/cloudius-systems/osv-apps/pull/24/files#diff-1>
>    (1)
>    - *A* erlang/os_mon/src/disksup.erl
>    <https://github.com/cloudius-systems/osv-apps/pull/24/files#diff-2>
>    (282)
>    - *A* erlang/os_mon/src/memsup.erl
>    <https://github.com/cloudius-systems/osv-apps/pull/24/files#diff-3>
>    (1025)
>    - *A* erlang/os_mon/src/os_mon.erl
>    <https://github.com/cloudius-systems/osv-apps/pull/24/files#diff-4>
>    (183)
>
> Patch Links:
>
>    - https://github.com/cloudius-systems/osv-apps/pull/24.patch
>    - https://github.com/cloudius-systems/osv-apps/pull/24.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudius-systems/osv-apps/pull/24>.
>



-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by nyh** [comment]
On Mon, May 4, 2015 at 1:01 PM, Nadav Har'El <nyh@cloudius-systems.com>
wrote:

> This patch includes over a thousand lines of Erlang code - where does it
> come from? If it comes from the Erlang distribution itself, why do we need
> to put it in osv-apps.git?
>

I see all these files come from otp_src_17.3/. So can you please, instead
of including them in our repository, copy them at build time?

If they require patching, you can patch them - you can see an example in
apps/memcached/GET, where after unpacking the source I patch it to fix
https://code.google.com/p/memcached/issues/detail?id=331

Now that I think of it, is the stuff in os_mon/c_src also stuff you copied
from otp_src_17.3? If so, can you please remove them from the repository,
and copy them at build time?

Thanks.

**Comment by bhuztez** [comment]
@nyh I think it is ok now.

**Comment by nyh** [comment]
On Wed, May 6, 2015 at 10:27 AM, bhuztez <notifications@github.com> wrote:

> @nyh <https://github.com/nyh> I think it is ok now.
>
>
I've committed your last pull  and now the example you gave in pull request
23 ( https://github.com/cloudius-systems/osv-apps/pull/23) seems to work
correctly now. Thanks!

I had to do a "cd apps/erlang; make clean" (or scripts/build clean) to
force a remaking of erlang for this to work correctly (it got confused by
old stuff remaining there from previous builds).

-- 
Nadav Har'El
nyh@cloudius-systems.com

**Pull request merged**
